### ISSUE TITLE
error CS1061: 'Stack<Container>' does not contain a definition for 'TryPop'

### ISSUE THREAD

**Issue by MexicanMan** [gustavopsantos/Reflex#10]
After installation attmept of Reflex version 2.0.0 on Unity 2020.3.36f1, I got this error:
`Assets/Reflex/Scripts/Core/ContainerStack.cs(27,27): error CS1061: 'Stack<Container>' does not contain a definition for 'TryPop' and no accessible extension method 'TryPop' accepting a first argument of type 'Stack<Container>' could be found (are you missing a using directive or an assembly reference?)`

MSDN documentation says that `TryPop` available only on .NET Standard 2.1 ([here](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.stack-1.trypop?view=net-6.0)). However, .NET Standard 2.1 became available only on Unity 2022.1, whereas repo readme says that Reflex supports Unity 2019+. Is Reflex v2.0.0 supposed to work only on Unity 2022 now?

**Comment by belikovdev** [comment]
Hi @MexicanMan! It is a known issue. Basically if u want you can easily fix it locally. The update will be released later.
Here is how Dispose method can be rewritten to fix the issue:
` public void Dispose()
        {
            while (_stack.Count > 0)
            {
                _stack.Pop().Dispose();
            }
        }`

**Comment by gustavopsantos** [comment]
Hello @MexicanMan, `.NET Standard 2.1` its already available on Unity 2021 LTS. However yes, Reflex should still support unity 2019+, so Im pushing a fix for it right now.
