### ISSUE TITLE
Can`t resolve dependencies from SceneInstaller if use ProjectInstaller too.

### ISSUE THREAD

**Issue by Hafune** [gustavopsantos/Reflex#18]
Hi.
If i use ProjectInstaller i catn`t resolve dependencies which was binding in SceneInstaller,
i use method BindInstanceAs and try bind object from scene, from [SerializableField].

**Comment by Hafune** [comment]
p.s. 
In method GetInjectables - MonoInjectionMode.Recursive - GetComponentsInChildren need add argument includeInactive = true, because inactive children don't get dependencies when we use container.Instantiate()

![image](https://user-images.githubusercontent.com/58075695/210205652-8739228e-704a-4e70-9b82-16ddbb3e637d.png)

**Comment by gustavopsantos** [comment]
Thanks @Hafune for spoting the issue.
Its fixed and released at version [3.5.2](https://github.com/gustavopsantos/Reflex/releases/tag/3.5.3)
