### ISSUE TITLE
Can't Instantiate object from IInstaller

### ISSUE THREAD

**Issue by skelitheprogrammer** [gustavopsantos/Reflex#24]
I want to instantiate gameobject from assets when scene injection is completed. I used that before, when Container was the main thing to bind everything. Do I need to make a new way of how to spawn this gameobject? Create a script that will get Container to spawn the gameobject? Or Forget about SceneContext and handle myself?

![изображение](https://user-images.githubusercontent.com/47909066/232333267-090a9a5d-469a-4d1b-aacc-814b2c918754.png)
![изображение](https://user-images.githubusercontent.com/47909066/232333285-fd145be0-5a45-47bb-a1ec-049be2d256d4.png)

```c#
public class SceneInstaller : MonoBehaviour, IInstaller
{
    [SerializeField] private SystemRunner _systemRunner;

    public void InstallBindings(ContainerDescriptor descriptor)
    {
        Container container = descriptor.Build();
        container.Instantiate(_systemRunner);
    }
}
```

**Comment by gustavopsantos** [comment]
Ohh, I think I forgot to add some public APIs. and Instantiate is one of them.
I'll fix it now, @skelitheprogrammer thanks for reporting it.

**Comment by gustavopsantos** [comment]
Ohh wait, I tought you were reporting that the Instantiate API was missing. I messed it up.
The problem is that you should not build the container there inside your scene installer.
This is the responsability of UnityInjector, and its done just after your `SceneInstaller::InstallBindings` are invoked.

Is this `_systemRunner` a prefab? If yes try the following:
Try adding a method like this to your `SceneInstaller`
```csharp
[Inject]
private void Inject(Container container)
{
    container.Instantiate(_systemRunner);
}
```

**Comment by skelitheprogrammer** [comment]
> 

Hi.

I tried to use Build() because i need container in order to spawn inside the SceneInstaller : IInstaller script like I used it before. Maybe not the best practice, but for my demo purposes was ok XD .

Yes, SystemRunner is a prefab gameobject. 

Code provided by you works but it feels a bit weird, but if its the new way (or the only way) than ok.
