### ISSUE TITLE
Question: Does Reflex support SignalBus and Decorator pattern like Zenject?

### ISSUE THREAD

**Issue by carlos-truong** [gustavopsantos/Reflex#37]
Hi,
Does Reflex support SignalBus and Decorator pattern like Zenject?

I like these two features of Zenject but it seems that Reflex doesn't have these features.
Will Reflex add these features in the future?

**Comment by gustavopsantos** [comment]
Hello 👋 

Does Reflex support SignalBus? 
It does not

Will Reflex support SignalBus in the future?
No, but this is something you can easily implement by yourself with a few objects.
You can have for instance a NotificationContainer that you can bind to your scopes as you wish.
Heres an example of a implementation: https://www.youtube.com/watch?v=NmmpXcMxCjY

Does Reflex support Decorators?
It does not

Will Reflex support Decorators in the future?
Very likely not, as it breaks the concept of container immutability
