### ISSUE TITLE
Question: Async data

### ISSUE THREAD

**Issue by mxkacsa** [gustavopsantos/Reflex#38]
Hello!
What would be a suitable scenario for an application that needs to load remote configuration from an API or load configuration from a file? One approach could involve creating an Initialization scene and transitioning to another scene after the configuration is loaded. However, a challenge arises when using the editor mode and pressing 'Play' on a different game scene. In such cases, it becomes necessary to load the Initialization scene. Unfortunately, calling `ReflexSceneManager.LoadScene` from the `IInstaller` in the Menu scene (whether in `Awake`, `Start`, or `InstallBindings` methods) can lead to freezing issues in the editor. (2022.3.7f1)

How do others handle asynchronous calls with Reflex?

**Comment by gustavopsantos** [comment]
Sorry for late reply, I didnt received any notification about your question.
The usually best approach is to as you described, to load all the remote configuration on a boot scene for instance, construct all the dependencies you need, and open your game scene by:

```            
ReflexSceneManager.LoadScene("Gameplay", LoadSceneMode.Single, descriptor =>
{
    descriptor.AddSingleton...
    descriptor.AddSingleton...
    descriptor.AddSingleton...
});
```

So you still respect the immutability of the container while providing for example different implementation for your services depending on a remote configutation.

Regarding the editor issue, I dont think you should care much about it, but yeah I agree, is annoying to remember to open the correct scene before entering playmode, however I see this as the industry standard, I never worked on a project that does not force you to do this.
However I found this repo here:
https://github.com/CSaratakij/SceneSelector
that seems to solve this issue, so you can definetely try this out
