### ISSUE TITLE
Runtime injection

### ISSUE THREAD

**Issue by MaratValeev** [gustavopsantos/Reflex#41]
Is it posible inject things for instantiated entites?

**Comment by gustavopsantos** [comment]
@MaratValeev 
Yes, it is possible, you can use:
```csharp
AttributeInjector.Inject(myEntity, container);
```

Using that API, all fields, properties and methods of your `myEntity` annotated with Inject attribute will be injected ;)
For quick questions I recommend you join our community on discord https://discord.gg/XM47TsGScH
