### ISSUE TITLE
NRE with MonoBehaviour's [Inject] attribute when it's child of DontDestroyOnLoad game object

### ISSUE THREAD

**Issue by Leksay** [gustavopsantos/Reflex#43]
NRE with MonoBehaviour's [Inject] attribute when it's child of DontDestroyOnLoad game object

**To Reproduce**
1. Create a scene and add empty object (A). Add script that makes object DontDestroyOnLoad.
2. Create a child of (A) game object. Add some script with field/property (B) with [Inject] attribute. In this script add reference to (B ) property.
3. Add project context, bind as singletone with same type as B property.

**Expected behavior**
Dependency injected, property is not null.

Find this issue with unity 2022.3.16.

![изображение](https://github.com/gustavopsantos/Reflex/assets/43336918/e540d51e-f65d-4b11-926b-60c3e27c09c0)
![изображение](https://github.com/gustavopsantos/Reflex/assets/43336918/a71ced9f-167d-4e1f-be4b-9074bb17395b)
![изображение](https://github.com/gustavopsantos/Reflex/assets/43336918/ef80b0bc-dd54-4d25-b1da-85faf6bfc9ba)
![изображение](https://github.com/gustavopsantos/Reflex/assets/43336918/2827d877-7d8c-4d3d-926a-cbee7c9fbaa6)
![изображение](https://github.com/gustavopsantos/Reflex/assets/43336918/aa5908db-a4ec-4bda-899d-83cec37458e0)
![изображение](https://github.com/gustavopsantos/Reflex/assets/43336918/fabc2ca2-7dc8-43f6-b111-39e2024be9d2)

**Comment by Leksay** [comment]
Seems I know why is doesn't work.
It's all because injector get all MonoBehaviours on active scene with extension method All<T> (SceneExtensions.cs).

I move object to DontDestroyOnLoadScene in Awake() and when Injector collects all MonoBehs from active scene my MonoBeh is already in other scene (DontDestroyOnLoad).

**Comment by gustavopsantos** [comment]
@Leksay You are fully correct about your assumptions, Reflex finds and injects monobehaviours on scene in between Awake and Start.
So by moving it out of the scene on Awake prevents Reflex from finding it.
