### ISSUE TITLE
Styles class in DebuggingWindow causes conflicts with Dialogue System from Pixel Crushers

### ISSUE THREAD

**Issue by Lamonin** [gustavopsantos/Reflex#49]
Tried to upgrade Reflex from version 4.4.1 to version 5.0.0 (because it's the only new version that doesn't cause problems like I thought it would), however after upgrading I get the following errors.

![image](https://github.com/gustavopsantos/Reflex/assets/48371419/8d3738ac-7a20-41e0-b709-ffc31eedc2b5)

It seems that because Styles both there and there does not lie in any namespace it causes a name conflict. I then tried updating Reflex to the latest version, however that didn't solve the problem either.

**Comment by gustavopsantos** [comment]
@Lamonin Hmmm indeed, reflex Styles class are missing the namespace definition, im gonna push a hotfix for that now.
Thanks for pointing this out!

**Comment by gustavopsantos** [comment]
@Lamonin issue solved at https://github.com/gustavopsantos/Reflex/releases/tag/8.0.1
