### ISSUE TITLE
Debugger Layout Wrapping

### ISSUE THREAD

**Issue by boraty14** [gustavopsantos/Reflex#55]
![Screenshot 2024-06-03 141230](https://github.com/gustavopsantos/Reflex/assets/85781952/4aec51f9-135d-4fa3-9814-8f6d9c1e5695)

I am using Unity 6000.0.4f1, and it seems like Unity introduced a new bug for imgui because debugger was fine when I was checking it out at 2022.3.X versions.

![Screenshot 2024-06-03 141257](https://github.com/gustavopsantos/Reflex/assets/85781952/23897259-bc66-4dbe-873f-b00b9df551b8)
A temporary fix I found is either setting wordWrap to false or adding some kind of offset to rect.width in MultiColumnTreeView.cs, I was gonna make a pr but don;t know if there is a better way to fix it so I did not :D

**Comment by gustavopsantos** [comment]
Yeah, it seems like setting word wrap to false is the correct solution for this case, thanks for finding it, I'll be pushing a fix for it right now

**Comment by gustavopsantos** [comment]
Issue fixed at https://github.com/gustavopsantos/Reflex/releases/tag/8.3.1, thanks @boraty14 for finding it ;)
