### ISSUE TITLE
Inject in non-MB

### ISSUE THREAD

**Issue by cckelly** [gustavopsantos/Reflex#58]
This is more a question about how this works as it wasn't clear to me. Is there a way to use the Inject attribute in a non-monobehaviour? For example:

```
    public class MyTestClass
    {
        [Inject] private readonly MyInjectableClass _myClass;
    }
```
MyTestClass will be instantiated repeatedly throughout my app's lifecycle.

**Comment by gustavopsantos** [comment]
Answered this already in discord: https://discord.com/channels/1098008290052546731/1100153692054880366/1255521210356334592
