### ISSUE TITLE
Comparison benchmark with ManualDI

### ISSUE THREAD

**Issue by PereViader** [gustavopsantos/Reflex#65]
Hello!
Author of the library https://github.com/PereViader/ManualDi 

Would you be interested in having comparison benchmarks with my library? 

This would require bumping the Unity version, which I understand might not be desired https://github.com/gustavopsantos/Reflex/blob/main/ProjectSettings/ProjectVersion.txt

I'd be happy to take care of the implementation if this is something you're open to.

Let me know your thoughts!

**Comment by gustavopsantos** [comment]
Hello @PereViader 
The more comparisons we have the better, but why it would require bumping the unity version of the repository? Don't you just need to import the package with the git url provided in the readme?
The package should work even in unity 6.

**Comment by PereViader** [comment]
Hello @gustavopsantos. The repository currently has unity version `2021.3.10f1` which, if memory serves me right, has access to Microsoft Roslyn source generators version 3.8. 
Because my library uses incremental source generators, it must use a version above 4.0 which started happening on unity `2022.3.29` with verison 4.1 (Telling this from memory)

I do a sample PR and have the benchmark conditionally compiled with the unity version if you want.

**Comment by gustavopsantos** [comment]
Ohh I see, yeah that would required the version bump.
It would be great to have that comparison too, however I'm planning to bump minimum version to `2022` only when unity 6 LTS is launched. So lets talk again when I do bump the version ;)
